prd:
  catalog_name: mlops_prd
  schema_name: steven
acc:
  catalog_name: mlops_acc
  schema_name: steven
dev:
  catalog_name: mlops_dev
  schema_name: steven

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 10 # changed from 6


num_features:
  - aantal_zitplaatsen
  - aantal_cilinders
  - cilinderinhoud
  - massa_ledig_voertuig
  - massa_rijklaar
  - catalogusprijs
  - aantal_deuren
  - aantal_wielen
  - lengte
  - breedte
  - vermogen_massarijklaar
  - wielbasis
  - days_alive 
  - nettomaximumvermogen
  - vervaldatum_apk
  - datum_eerste_toelating

cat_features:
  - kenteken
  - voertuigsoort
  - merk
  - handelsbenaming
  - inrichting
  - eerste_kleur
  - type
  - tellerstandoordeel
  - brandstof_omschrijving

target: is_dead
