prd:
  catalog_name: mlops_prd/steven
  schema_name: gekentekende_voertuigen
acc:
  catalog_name: mlops_acc/steven
  schema_name: gekentekende_voertuigen
dev:
  catalog_name: mlops_dev/steven
  schema_name: gekentekende_voertuigen

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6


num_features:
  - aantal_zitplaatsen
  - aantal_cilinders
  - cilinderinhoud
  - massa_ledig_voertuig
  - massa_rijklaar
  - catalogusprijs
  - aantal_deuren
  - aantal_wielen
  - lengte
  - breedte
  - vermogen_massarijklaar
  - wielbasis
  - days_alive
  - vermogen
  - vervaldatum_apk
  - datum_eerste_toelating

cat_features:
  - kenteken
  - voertuigsoort
  - merk
  - handelsbenaming
  - inrichting
  - eerste_kleur
  - type
  - tellerstandoordeel
  - brandstoftype

target: is_dead
